# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb2fasthtml',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/nb2fasthtml',
                'lib_path': 'nb2fasthtml'},
  'syms': { 'nb2fasthtml.core': { 'nb2fasthtml.core._fm2dict': ('core.html#_fm2dict', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core._md2dict': ('core.html#_md2dict', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.get_frontmatter': ('core.html#get_frontmatter', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.get_nb_lang': ('core.html#get_nb_lang', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.render_code_output': ('core.html#render_code_output', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.render_code_source': ('core.html#render_code_source', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.render_frontmatter': ('core.html#render_frontmatter', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.render_md': ('core.html#render_md', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.render_md_cell': ('core.html#render_md_cell', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.render_nb': ('core.html#render_nb', 'nb2fasthtml/core.py'),
                                  'nb2fasthtml.core.strip_list': ('core.html#strip_list', 'nb2fasthtml/core.py')}}}
